#!/bin/bash
cd /home/pi/iot-furnace

logstaship=$(/usr/local/bin/iot-furnace prop logstashIp)
logstashport=$(/usr/local/bin/iot-furnace prop logstashPort)
iotid=$(/usr/local/bin/iot-furnace prop deviceName)

gitstatus=$(git pull)
if [ "${gitstatus}" = "Already up-to-date." ]; then
  /bin/echo "iot-furnace-${iotid}:INFO: No changes in repository (iot-upgrade)" > /dev/udp/${logstaship}/${logstashport}
else
  /usr/bin/git pull
  /usr/bin/mvn clean install
  /usr/bin/crontab /home/pi/iot-furnace/src/main/bash/crontab-raspi
  /bin/echo "iot-furnace-${iotid}:INFO: Update completed (iot-upgrade)" > /dev/udp/${logstaship}/${logstashport}
fi

exit 0
