#!/bin/bash
# respberry pi setup script for iot-solar
# first run sudo apt-get -y install git && git clone https://github.com/jstelwag/iot-furnace
# then sh iot-furnace/src/main/bash/setup

sudo apt-get update
sudo apt-get -y upgrade

sudo apt-get -y install cron-apt rpi-update
#sudo rpi-update
sudo apt-get -y install redis-server
sudo apt-get -y install openjdk-8-jdk maven
#sudo apt-get -y install collectd
#sudo apt-get -y install librxtx-java

# allow debugging via pu to I2CMaster
sudo apt-get install I2CMaster-tools
sudo adduser pi I2CMaster
echo 'I2CMaster-dev' | sudo tee --append /etc/modules
echo 'dtparam=i2c_arm=on' | sudo tee --append /boot/config.txt

# you must reboot in order to use I2CMaster

cat <<EOF >iot.conf
iot.id=kasteel_zolder
influx.ip=192.168.
influx.port=8087
usb.furnace=/dev/ttyUSB0
usb.valvegroup=/dev/ttyACM0
logstash.ip=192.168.
logstash.port=9000
monitor.ip=192.168.
monitor.port=8000
services=FurnaceSlave,ValveGroupSlave,FurnaceMonitor
loggers=FluxLogger
EOF
sudo mv iot.conf /etc

cd /tmp
cat <<EOF >iot-upgrade
#!/bin/bash
cd /home/pi/iot-furnace
git pull
sh src/main/bash/iot-upgrade
/usr/bin/crontab /home/pi/iot-furnace/src/main/bash/crontab
EOF
sudo mv iot-upgrade /usr/local/bin
sudo chmod +x /usr/local/bin/iot-upgrade

cat <<EOF >iot-furnace
#!/bin/bash
sh /home/pi/iot-furnace/src/main/bash/iot-furnace $1
exit 0
EOF
sudo mv iot-furnace /usr/local/bin
sudo chmod +x /usr/local/bin/iot-furnace

cd ~
iot-upgrade

# test if this works
#sudo usermod -a -G tty pi

sudo nano /etc/iot.conf

exit 0