#!/bin/bash
# respberry pi setup script for iot-solar
# first run sudo apt-get -y install git && git clone https://github.com/jstelwag/iot-furnace
# then sh iot-furnace/src/main/bash/setup

sudo apt-get update
sudo apt-get -y upgrade

sudo apt-get -y install cron-apt rpi-update redis-server openjdk-11-jdk maven
#sudo rpi-update

#Install from apache, ignore debian maven package (untill they upgrade beyond 3.6.0)
#cd
#wget http://mirror.serverion.com/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
#tar xzvf apache-maven-3.6.3-bin.tar.gz
#echo 'PATH="$PATH:/home/pi/apache-maven-3.6.3/bin"' >> .profile

# allow debugging via pu to I2CMaster
sudo apt-get -y install i2c-tools
sudo adduser pi i2c
echo 'i2c-dev' | sudo tee --append /etc/modules
echo 'dtparam=i2c_arm=on' | sudo tee --append /boot/config.txt
# check with
# i2cdetect -y 1

# you must reboot in order to use i2c

sudo apt-get -y install wiringpi
curl -sSL https://pi4j.com/install | sudo bash

cd /tmp
cat <<EOF >iot-upgrade
#!/bin/bash
/bin/bash /home/pi/iot-furnace/src/main/bash/iot-upgrade
exit 0
EOF
sudo mv iot-upgrade /usr/local/bin
sudo chmod +x /usr/local/bin/iot-upgrade

cat <<EOF >iot-furnace
#!/bin/bash
/bin/bash /home/pi/iot-furnace/src/main/bash/iot-furnace \$@
exit 0
EOF
sudo mv iot-furnace /usr/local/bin
sudo chmod +x /usr/local/bin/iot-furnace

cd /home/pi/iot-furnace
mvn clean install

# test if this works
#sudo usermod -a -G tty pi

cat <<EOF >i2c.service
[Unit]
Description=Java i2c master Service
[Service]
User=pi
# The configuration file application.properties should be here:
#change this to your workspace
WorkingDirectory=/home/pi
#path to executable.
#executable is a bash script which calls jar file
ExecStart=/usr/local/bin/iot-furnace I2CMaster
TimeoutStopSec=10
Restart=on-failure
RestartSec=5
[Install]
WantedBy=multi-user.target
EOF

sudo mv i2c.service /etc/systemd/system/

sudo systemctl daemon-reload
sudo systemctl enable i2c.service
sudo systemctl start i2c
sudo systemctl status i2c

cat <<EOF >http.service
[Unit]
Description=Java http service
[Service]
User=pi
# The configuration file application.properties should be here:
#change this to your workspace
WorkingDirectory=/home/pi
#path to executable.
#executable is a bash script which calls jar file
ExecStart=/usr/local/bin/iot-furnace http
TimeoutStopSec=10
Restart=on-failure
RestartSec=5
[Install]
WantedBy=multi-user.target
EOF

sudo mv http.service /etc/systemd/system/

sudo systemctl daemon-reload
sudo systemctl enable http.service
sudo systemctl start http
sudo systemctl status http

cat <<EOF >i2c-watchdog
#!/bin/bash
if [[ $(redis-cli --raw exists boiler120.state) = 0 ]]; then
#  logstaship=$(iot-furnace prop logstashIp)
#  logstashport=$(iot-furnace prop logstashPort)
#  iotid=$(iot-furnace prop deviceName)

  echo "iot-furnace-${iotid}:WARN: Restarting i2c by watchdog" > /dev/udp/192.168.178.101/9000

  sudo systemctl stop i2c
  wait 10s
  sudo systemctl start i2c
fi

exit 0
EOF

chmod +x i2c-watchdog
sudo mv i2c-watchdog /usr/local/bin

sudo tee -a /etc/wpa_supplicant/wpa_supplicant.conf << EOF
network={ ssid="Kasteel keuken"
        #psk="bnbkasteel"
        psk=3beceea36990848d10b1c3cb5b14805cf8516b93ec679bd699ac0ca58accd677
}
network={ ssid="Kasteel hal"
        #psk="bnbkasteel"
        psk=7e532d31523df37698c9db4ce01a5c5304c2126304237ab3b8c0ea6ffe3c4516
}
EOF

sudo tee -a sudo nano /boot/config.txt << EOF
gpu_mem=16
dtoverlay=w1-gpio
EOF

# run this after reboot
sudo modprobe w1–gpio
sudo modprobe w1-therm
# somehow this soes not work. use raspi-config to enable 1-wire

exit 0
